# syntax=docker/dockerfile:1

FROM public.ecr.aws/lambda/nodejs:20 AS build
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:20
WORKDIR ${LAMBDA_TASK_ROOT}
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /build/dist ./dist

CMD ["dist/lambda.handler"]
